site_name: NewRelic Docs
repo_url: https://github.com/JonkyOps/NewRelic
theme: readthedocs
pages:
  - Home: index.md
  - NewRelic Cmdlets:
    - Invoke-NRRequest: Invoke-NRRequest.md
    - Get-NRApplication: Get-NRApplication.md
    - Get-NRTimeSpan: Get-NRTimeSpan.md
    - Invoke-NRQLQuery: Invoke-NRQLQuery.md
